# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
author: Jamie Simon
email: jsi@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog

title: J S
url: "http://james-simon.github.io"
imgurl: "https://james-simon.github.io/img"

github_username:  james-simon
insta_username: sam.simon17

DBL: "https://dl.dropboxusercontent.com/u/16348658"
excerpt_separator: <!--exc-->

# Build settings
markdown: kramdown
highlighter: rouge
